server:
  port: 8089

spring:
  application:
    name: config-cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JioCoders/ms-config.git
          clone-on-start: true
