server:
  port: 8090
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb//:user-service
        predicates:
          - Path=/user/**
      - id: department-service
        uri: lb//:department-service
        predicates:
          - Path=/dept/**