spring:
  application:
      name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
#   h2:
#     console.enabled: true
#   datasource:
#     url: jdbc:h2:file:/h2db/deptdb
#     username: sa
#     password: pass
#     driverClassName: org.h2.Driver

  