spring:
  application:
      name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"
#   h2:
#     console.enabled: true
# spring.sql.init.platform=h2
#   datasource:
#     url: jdbc:h2:file:/h2db/userdb
#     username: sa
#     password: pass
#     driverClassName: org.h2.Driver
# spring.jpa.defer-datasource-initialization=true
# # spring.jpa.hibernate.ddl-auto=update

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userDeptBreaker: 
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  retry:
    instances:
      userDeptRetry: 
        max-attempts: 3
        wait-duration: 5s
